[recorder]
	interval = 60 #seconds
	path = "./dashboard/input/records"
	[recorder.id]
		group = 4181328
		place = 9795212770

[format]
	[format.fill_down]
		enabled = false
		recursive = true

	[format.input]
		path = "./dashboard/input"

	[format.output]
		path = "./dashboard/output"
[encoding]
	marker = "~"
	hash = "2d1cab07-ae78-4c38-b929-7f4892199a4c"
	[encoding.dictionary]	
		[encoding.dictionary.properties]
			"Audience" = "a"
			"Badges" = "b"
			"Build" = "c"
			"Cash" = "d"
			"Checkpoint" = "e"
			"Client" = "f"
			"FPS" = "g"
			"Friends" = "h"
			"Heartbeat" = "i"
			"Inventory" = "j"
			"IsTeenager" = "k"
			"Language" = "l"
			"LeftRight" = "m"
			"Lua" = "n"
			"Major" = "o"
			"Map" = "p"
			"MessageCount" = "q"
			"Memory" = "r"
			"Minor" = "s"
			"Name" = "t"
			"Patch" = "u"
			"Hotfix" = "v"
			"Parts" = "w"
			"PlaceId" = "x"
			"Performance" = "y"
			"Physics" = "z"
			"Ping" = "A"
			"Progress" = "B"
			"Products" = "C"
			"Server" = "D"
			"Total" = "E"
			"Render" = "F"
			"Network" = "G"
			"Graphic" = "H"
			"Texture" = "I"
			"Sound" = "J"
			"Social" = "K"
			"ServerFill" = "L"
			"Section" = "M"
			"Version" = "N"
			"Vehicles" = "O"	
		[encoding.dictionary.values]
			[encoding.dictionary.values."Map"]
				[encoding.dictionary.values."Map"."Name"]
					"Dunes" = "P"
				[encoding.dictionary.values."Map"."Section"]
					"Dam" = "Q"
				[encoding.dictionary.values."Map"."Checkpoint"]
					"MilitaryBase" = "R"

	[encoding.arrays]
		[encoding.arrays."Inventory"]
			"Vehicles" = [
				"CarA",
				"CarB",
				"CarC",
				"CarD",
				"CarE",
				"CarF",
				"CarG",
				"CarH",
				"CarI",
				"CarJ",
				"CarK",
				"CarL",
				"CarM",
				"CarN",
				"CarO",
				"CarP",
				"CarQ",
				"CarR",
				"CarS",
				"CarT",
			]
			"Badges" = [
				"BadgeA",
				"BadgeB",
				"BadgeC",
				"BadgeD",
				"BadgeE",
				"BadgeF",
				"BadgeG",
				"BadgeH",
				"BadgeI",
				"BadgeJ",
				"BadgeK",
				"BadgeL",
				"BadgeM"
			]
			"Products" = [
				"ProductA",
				"ProductB",
				"ProductC",
				"ProductD",
				"ProductE",
				"ProductF",
				"ProductG",
				"ProductH",
			]