[package]
name = "nightcycle/midas"
description = "Turn every game you touch to gold with a comprehensive analytics suite!"
version = "2.0.4"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
